### PR TITLE
[ja] Add Japanese Translation

### PR DESCRIPTION
**Pull request by EveChen**

### CODE REVIEW

**Comment by EveChen** [comment]
@ccwang002 Assist me to merge

**Comment by ccwang002** [comment]
@EveChen Let me know if all jp pages are done.

**Comment by EveChen** [comment]
@ccwang002 Got it! I had finished the accommodation just few minutes ago. Will notify you once I finish all jp pages.

**Comment by ccwang002** [comment]
Thanks for your hard work! I see no encoding error

**Pull request merged**
