### PR TITLE
[ja] update registration

### PR DESCRIPTION
**Pull request by EveChen**
@ccwang002 
I had updated the latest version of registration page in Japanese.
Please help me merge. Thanks!

### CODE REVIEW

**Comment by ccwang002** [comment]
Thanks! 

Oh I found that I haven't told you how to do a upstream sync, so now it cannot be automatically merged. Hmm.. I will do this my self, after this pull request, could you follow [this reference](http://stackoverflow.com/a/15943715) and try sync with upstream yourself?

It might be a little bit hard (some command line interaction involved), but I think you can make it :) Let me know if any error occurs.

**Comment by EveChen** [comment]
I got it! I would read the reference you gave by myself.

But since I need to take the midterm exam this Friday, I may not able to do
it immediately.
Hope you could do it for me until this Friday.
Thanks!

2015-04-08 23:14 GMT+08:00 Liang Bo Wang notifications@github.com:

**Comment by ccwang002** [comment]
Take your time. Thanks again for your kindly help!

**Comment by yenchiayi** [comment]
Hi Eve,
我把之前亮亮教我的指令整理起來了，也可以參考這個文件喔~
https://docs.google.com/document/d/1-Q8IWwP0Gs-WbZqlBpA0a7C1MkxsilbvhvQc0RGfW0w/edit?usp=sharing

**Comment by EveChen** [comment]
Hello,

謝謝你的整理：Ｄ
等我期中考結束後再來好好研究~

話說...請問你是Yen嗎? XD

Eve

2015-04-08 23:44 GMT+08:00 exilespacer notifications@github.com:

**Pull request merged**
